### ISSUE TITLE
Missing a Database

### ISSUE THREAD

**Issue by samuel-ma** [samuel-ma/Gesa#1]
Intergrate MongoDB to the site

**Comment by VanshVg** [comment]
Hey can you please tell me in what folder/file should i add mongoDB configuration code so i can work on it??

**Comment by samuel-ma** [comment]
@VanshVg 
If you'd like to contribute, plz go ahead
In folder is just fine, but preferably the data folder would work just fine

**Comment by VanshVg** [comment]
> @VanshVg If you'd like to contribute, plz go ahead In folder is just fine, but preferably the data folder would work just fine

To integrate mongoDB into project we need to create a server side code differently.
We can't really integrate mongoDB directly to client side code so i'd suggest you to create server side folder and add backend of the project separately.

**Comment by samuel-ma** [comment]
There's a data file in the server folder
Lemme just update it

**Comment by VanshVg** [comment]
Ok cool.
Will work on it shortly thanx.
